function plotActUtil(act_util, times, alpha)
tt=times(2,1,:);
% plot activity utility
figure
grid on
hold on
x = 13:12+size(act_util,1);
colors = lines(2);
plot(x, act_util(:,1),...
    'LineStyle', ':', ...
    'Marker', '^', ...
    'Color', colors(1,:), ...
    'LineWidth', 2, ...
    'MarkerSize', 6, ...
    'MarkerFaceColor', colors(1,:));
plot(x, act_util(:,2), ...
    'LineStyle', ':', ...
    'Marker', 'v', ...
    'Color', colors(2,:), ...
    'LineWidth', 2, ...
    'MarkerSize', 6, ...
    'MarkerFaceColor', colors(2,:));
set(gca,'XTick',13:24)
ylim([min(-tt(:).*alpha)*1.2 max(act_util(:))*1.4])
xlim([12 25])
legend('Home', 'Work', 'Location', 'NorthWest')
xlabel('Time (o''clock)')
ylabel('Activity Utiliy')

% plot travel time
ax1 = gca;
set(ax1,'XColor','k','YColor','k')
ax2 = axes('Position',get(ax1,'Position'),...
           'XAxisLocation','top',...
           'XTick', [], ...
           'YAxisLocation','right',...
           'Color','none',...
           'XColor','r','YColor','r');
line(x, -tt(:).*alpha, 'LineStyle', ':', ...
               'Color', 'r', ...
               'LineWidth', 2, ...
               'Marker','o', ...
               'MarkerSize', 6,...
               'MarkerFaceColor', 'r', ...
               'Parent',ax2);
ylim([min(-tt(:).*alpha)*1.2 max(act_util(:))*1.5])
xlim([12 25])
ylabel('Travel Disutility')
legend_h = legend('Travel from W to H', 'Location', 'NorthEast');
set(legend_h, 'Color', 'none')
